#!/usr/bin/env node

var cli = require('./build/cli')
var app = new cli.CLI();
var commandArgs = process.argv.slice(2);

app.exec(commandArgs).then(function(status) {
	process.exit(status);
}).done();

