#!/usr/bin/env node

var agent = require('./build/cli/agent');
var cli = require('./build/cli/cli')
var keyAgent = new agent.HttpKeyAgent();
var app = new cli.CLI(null /* console IO */, keyAgent);
var commandArgs = process.argv.slice(2);

if (typeof Map === 'undefined') {
	require('es6-collections');
}

app.exec(commandArgs).then(function(status) {
	process.exit(status);
}).done();

