#!/usr/bin/env node

var agent = require('./build/cli/agent');
var cli = require('./build/cli/cli')
var keyAgent = new agent.HttpKeyAgent();
var app = new cli.CLI(null /* console IO */, keyAgent);
var commandArgs = process.argv.slice(2);

if (typeof Map === 'undefined') {
	console.error('Passcards requires Node.js >= 0.12 or later.');
	console.error('You are currently using %s', process.version);
	process.exit(1);
}

app.exec(commandArgs).then(status => {
	process.exit(status);
}).catch(err => {
  console.error(err.message);
  process.exit(1);
});

